Neos:
  Imagine:
    driver: Imagick
  Flow:
    http:
      trustedProxies:
        proxies: '*'
    core:
      subRequestIniEntries:
        memory_limit: 2048M
    persistence:
      backendOptions:
        driver: '%env:NEOS_DB_DRIVER%'
        dbname: '%env:NEOS_DB_NAME%'
        user: '%env:NEOS_DB_USER%'
        password: '%env:NEOS_DB_PASSWORD%'
        host: '%env:NEOS_DB_HOST%'
        port: '%env:NEOS_DB_PORT%'
    i18n:
      defaultLocale: en
      fallbackRule:
        order: ['en']
    mvc:
      routes:
        'Base.Theme':
          position: 'start'
        'Neos.Neos':
          variables:
            defaultUriSuffix: ''
  Neos:
    userInterface:
      defaultLanguage: en
      navigateComponent:
        nodeTree:
          loadingDepth: 1
        structureTree:
          loadingDepth: 0
      translation:
        autoInclude:
          Base.Theme:
            - 'NodeTypes/*'
    nodeTypes:
      groups:
        teaser:
          label: Teaser
          position: 500
