Jonnitto:
  OutdatedBrowser:
    disableForCrawler: false
  ImagesInARow:
    lazy: true
  PrettyEmbedHelper:
    enableGdprMessage: true
    wrapper: 'jonnitto-prettyembed-wrapper px-safe'
  PrettyEmbedVideoPlatforms:
    defaults:
      color: db2725
  StadiaMaps:
    defaultCountry: DE
    aspectRatio: '16 / 9'
    settings:
      pinColor: '#26224C'
