name: neos-by-example
type: php
docroot: Web
php_version: '8.0'
webserver_type: nginx-fpm
router_http_port: '80'
router_https_port: '443'
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: '10.6'
mysql_version: ''
nfs_mount_enabled: false
use_dns_when_possible: true
mutagen_enabled: true
composer_version: '2'
omit_containers: [dba]
timezone: Europe/Berlin
hooks:
  post-start:
    - exec: mkdir -pv Data/Logs >> /dev/null
  post-composer:
    - exec: ./flow flow:package:rescan >> /dev/null
web_environment:
  - FLOW_CONTEXT=Development/ddev
  - FLOW_REWRITEURLS=1
  - FLOW_PATH_TEMPORARY_BASE=/tmp/neos
  - FLOW_ROOTPATH=/var/www/html
  - NEOS_DB_HOST=db
  - NEOS_DB_NAME=db
  - NEOS_DB_USER=db
  - NEOS_DB_PASSWORD=db
  - NEOS_DB_DRIVER=pdo_mysql
